In [ ]:
"""
6.1 : Numpy 1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression names after Vandermonde.
"""

In [1]:
# Assignment 6.1
# _______________________

import numpy as np
x=np.array([1,2,3,4,5,6,7])
N=len(x)
Z=np.column_stack([x**(N-i-1) for i in  range(N)])
print(Z)

[[     1      1      1      1      1      1      1]
 [    64     32     16      8      4      2      1]
 [   729    243     81     27      9      3      1]
 [  4096   1024    256     64     16      4      1]
 [ 15625   3125    625    125     25      5      1]
 [ 46656   7776   1296    216     36      6      1]
 [117649  16807   2401    343     49      7      1]]


In [2]:
# By using inbuilt numpy function vander.
import numpy as np
x=np.array([1,2,3,4,5,6,7])
a=np.vander(x,len(x))
print(a)

[[     1      1      1      1      1      1      1]
 [    64     32     16      8      4      2      1]
 [   729    243     81     27      9      3      1]
 [  4096   1024    256     64     16      4      1]
 [ 15625   3125    625    125     25      5      1]
 [ 46656   7776   1296    216     36      6      1]
 [117649  16807   2401    343     49      7      1]]
